variables:
  NODE_IMAGE: ${CI_REGISTRY_IMAGE}/node-20:latest

stages:
  - install
  - build
  - check

default:
  image: ${NODE_IMAGE}

.node-modules-cache:
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store
    policy: pull
  before_script:
    - echo -e "\e[0Ksection_start:`date +%s`:npm_install[collapsed=true]\r\e[0KInstalling dependencies"
    - pnpm config set store-dir .pnpm-store
    - pnpm install --prefer-offline
    - echo -e "\e[0Ksection_end:`date +%s`:npm_install\r\e[0K"

install:
  stage: install
  extends:
    - .node-modules-cache
  except:
    - tags
    - merge_requests
  cache:
    policy: pull-push
  script:
    - echo "This is a stub message"

build:
  stage: build
  extends:
    - .node-modules-cache
  except:
    - tags
    - merge_requests
  script:
    - pnpm build
  artifacts:
    paths:
      - build

lint:js:
  stage: check
  extends:
    - .node-modules-cache
  needs:
    - build
  except:
    - tags
    - merge_requests
  script:
    - pnpm lint:js

lint:css:
  stage: check
  extends:
    - .node-modules-cache
  needs:
    - build
  except:
    - tags
    - merge_requests
  script:
    - pnpm lint:css

lint:types:
  stage: check
  extends:
    - .node-modules-cache
  needs:
    - build
  except:
    - tags
    - merge_requests
  script:
    - pnpm lint:types
