export { default as banner1ImgUrl } from './ads-banner-1.jpg';
export { default as banner2ImgUrl } from './ads-banner-2.jpg';
export { default as bitcoinImgUrl } from './bitcoin.png';
export { default as markerImgUrl } from './marker.png';
export { default as mastercardImgUrl } from './mastercard.png';
export { default as noImgUrl } from './no-image.png';
export { default as paypalImgUrl } from './paypal.png';
export { default as securitySafetyImgUrl } from './security-safety.png';
export { default as visaImgUrl } from './visa.png';
